// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTEGDI1nVjY7HSXwHZz7BMDNRwfDlz4hY',
    appId: '1:820107268009:web:78724cec063db9834d7eb8',
    messagingSenderId: '820107268009',
    projectId: 'mys-cool-project',
    authDomain: 'mys-cool-project.firebaseapp.com',
    storageBucket: 'mys-cool-project.appspot.com',
    measurementId: 'G-K1JELPM9N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD33JQFcT3UKtszOazinLJ2gBxJ0yKgIpc',
    appId: '1:820107268009:android:c34ae664ae2586b94d7eb8',
    messagingSenderId: '820107268009',
    projectId: 'mys-cool-project',
    storageBucket: 'mys-cool-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVFXuzxjVN9-DhEk6DqKSF-wFv_48d2kE',
    appId: '1:820107268009:ios:217c1e7a47ba65b94d7eb8',
    messagingSenderId: '820107268009',
    projectId: 'mys-cool-project',
    storageBucket: 'mys-cool-project.appspot.com',
    iosClientId: '820107268009-nqk302vqrstn1e8bktcjkcbeolbqghgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
